services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '$POSTGRES_DB', '-U', '$POSTGRES_USER']
      interval: 5s
      retries: 5
    
  data_pipeline:
    build: 
      context: .
    volumes:
      - ./data_pipeline:/app/
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "./main.py"]

volumes:
  postgres_data: